### ISSUE TITLE
send data to the server manager

### ISSUE THREAD

**Issue by Al-Shetwi** [Khalid-Alqahtani/RCM3D#26]

**Comment by sloohkaa** [comment]
Issue moved to [Nawafinho/KSU #3](https://github.com/Nawafinho/KSU/issues/3) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sloohkaa** [comment]
Issue moved to [Nawafinho/KSU #2](https://github.com/Nawafinho/KSU/issues/2) via [**ZenHub**](https://www.zenhub.com/)
